<a href="https://colab.research.google.com/github/varshabantu/Data-Science-Tasks/blob/main/Datacleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data cleaning:** It is a process of removing unwanted data by extracting only wanted data.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv",encoding="ISO-8859-1")
df.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6454 non-null   int64
 1   mes       6454 non-null   object
 2   estado    6454 non-null   object
 3   numero    6322 non-null   object
 4   encontro  6454 non-null   object
dtypes: int64(1), object(4)
memory usage: 252.2+ KB

In [ ]:
#1) Renaming the columns
#   d = {"old_Col":"new_col"........}
#syntax:  df.rename(columns=d,inplace=True)
d = {"ano":"year","mes":"month",	"estado":"state",
     "numero":"no_of_fires","encontro":"date"}
df.rename(columns=d,inplace=True)
df

      year     month      state no_of_fires      date
0     1998   Janeiro       Acre     0 Fires  1/1/1998
1     1999   Janeiro       Acre     0 Fires  1/1/1999
2     2000   Janeiro       Acre     0 Fires  1/1/2000
3     2001   Janeiro       Acre     0 Fires  1/1/2001
4     2002   Janeiro       Acre     0 Fires  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  Dezembro  Tocantins         128  1/1/2012
6450  2013  Dezembro  Tocantins          85  1/1/2013
6451  2014  Dezembro  Tocantins         223  1/1/2014
6452  2015  Dezembro  Tocantins         373  1/1/2015
6453  2016  Dezembro  Tocantins         119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
#2)Dropping duplicate rows
#syntax:  df.drop_duplicates(inplace=True)
df.drop_duplicates(inplace=True)
df.shape

(6424, 5)

In [ ]:
#3)changing the data present in a column
#syntax:  d = {"old_data":"new_data".......}
#         df["col"] = df["col"].map(d)
#note: The len of dict should be equal to no.of unique values
d = {'Janeiro':"jan", 'Fevereiro':"feb", 'Março':"mar", 'Abril':"apr", 'Maio':"may", 'Junho':"jun", 'Julho':"jul",
       'Agosto':"aug", 'Setembro':"sep", 'Outubro':"oct", 'Novembro':"nov", 'Dezembro':"dec"}
df["month"] = df["month"].map(d)
df["month"].unique()

array(['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep',
       'oct', 'nov', 'dec'], dtype=object)

In [ ]:
#4)Applying inbuilt functions on a column
#syntax:  df[col] = df[col].str.fname(args)
df["month"] = df["month"].str.upper()
df["month"] = df["month"].str.lower()
df["month"] = df["month"].str.capitalize()
df

      year month      state no_of_fires      date
0     1998   Jan       Acre     0 Fires  1/1/1998
1     1999   Jan       Acre     0 Fires  1/1/1999
2     2000   Jan       Acre     0 Fires  1/1/2000
3     2001   Jan       Acre     0 Fires  1/1/2001
4     2002   Jan       Acre     0 Fires  1/1/2002
...    ...   ...        ...         ...       ...
6449  2012   Dec  Tocantins         128  1/1/2012
6450  2013   Dec  Tocantins          85  1/1/2013
6451  2014   Dec  Tocantins         223  1/1/2014
6452  2015   Dec  Tocantins         373  1/1/2015
6453  2016   Dec  Tocantins         119  1/1/2016

[6424 rows x 5 columns]

In [ ]:
#5) Removing unwanted data
# df["col"] = df["col"].str.strip("unwanted data")
df["no_of_fires"] = df["no_of_fires"].str.strip(" Fires")
df

      year month      state no_of_fires      date
0     1998   Jan       Acre           0  1/1/1998
1     1999   Jan       Acre           0  1/1/1999
2     2000   Jan       Acre           0  1/1/2000
3     2001   Jan       Acre           0  1/1/2001
4     2002   Jan       Acre           0  1/1/2002
...    ...   ...        ...         ...       ...
6449  2012   Dec  Tocantins         128  1/1/2012
6450  2013   Dec  Tocantins          85  1/1/2013
6451  2014   Dec  Tocantins         223  1/1/2014
6452  2015   Dec  Tocantins         373  1/1/2015
6453  2016   Dec  Tocantins         119  1/1/2016

[6424 rows x 5 columns]

In [ ]:
#6) Handling missing values:
df.dropna(inplace=True)
df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6292 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         6292 non-null   int64
 1   month        6292 non-null   object
 2   state        6292 non-null   object
 3   no_of_fires  6292 non-null   object
 4   date         6292 non-null   object
dtypes: int64(1), object(4)
memory usage: 294.9+ KB

In [ ]:
#7)changing the data type of col
#df[col] = df[col].astype(dest_dtype)
df["no_of_fires"] = df["no_of_fires"].astype(float)
df["no_of_fires"] = df["no_of_fires"].astype(int)
df["no_of_fires"].unique()

array([  0,  10,  12,   4,   1,   3,   5,   2,  11,  19,   7,   6,   8,
         9,  21,  27,  17,  40,  87,  45,  37,  39, 168,  42,  33,  29,
        41,  31, 126,  93,  71,  54,  60, 109, 533, 457, 130,  63, 136,
       396, 728, 645, 839, 960, 445, 194, 425, 739, 679, 509, 209, 265,
       290,  44,  18, 137, 687, 740, 461, 547, 316, 203, 652, 565, 292,
        97, 348, 258, 406, 905,  86,  15,  14,  74,  13,  79,  56,  46,
        98,  58, 150,  83,  55, 104,  23,  36,  49,  81,  24,  38,  20,
        16,  28,  32,  26,  52,  35,  70,  34,  25,  22,  30,  95, 162,
        76,  43,  50,  59, 155,  73,  88,  67, 112,  61, 128,  85, 192,
       142, 557, 355, 412, 335, 405, 395, 765, 304, 475, 385, 480, 827,
       793, 131, 157, 750, 949, 685, 207, 198, 266, 339, 282, 969, 341,
       484, 858,  84, 593, 200, 411, 123, 360, 422, 148, 354, 269, 491,
       158,  82,  53, 770,  65,  62,  92, 107, 275,  69,  64, 116, 140,
        51,  78,  90, 119, 146, 180, 177, 676, 108, 199, 640, 271, 234,
       248, 202, 356, 321, 259, 501, 741, 861, 267, 216, 189, 166, 928,
       911, 998, 479, 145, 332, 695, 725, 710, 545, 721, 215, 632, 889,
       694, 952, 244, 169, 261, 973, 399, 682, 220, 591, 552, 196, 147,
       102, 121,  80, 236, 293, 133, 114, 125, 439, 303, 225, 373, 314,
       297, 101, 179, 132, 256, 285, 154, 204, 223, 122, 143, 277, 113,
       235, 117, 206, 156, 231, 418, 100, 274, 115, 141, 135, 249, 404,
       363, 229, 281, 163, 110, 376,  89, 151, 103, 149, 183, 190,  94,
       106, 124, 120, 161, 326, 224, 144, 178, 118, 289, 211,  68, 270,
        72, 345, 208, 243, 242, 416, 329, 219, 310, 811, 519, 578, 906,
       362, 300, 815, 453, 633, 979, 948, 995, 611, 610, 674, 829, 724,
       699, 239, 402, 605, 288, 408, 174, 848, 423, 308, 226, 230, 477,
       164,  47, 264, 384, 347, 273,  91,  75, 111, 182, 278, 127, 590,
       801, 172, 185, 237, 241, 357, 609, 214, 370, 505, 309, 875, 581,
       964, 816, 435, 502, 415, 466, 517, 658, 575, 524, 669, 812, 276,
       397, 389, 631, 956, 643, 819,  48, 159,  99,  66,  96, 152,  77,
       105, 134, 186, 245, 246, 184, 173, 139, 263, 232, 318, 407, 625,
       467, 336, 446, 707, 462, 559, 769, 959, 901, 528, 616, 417, 914,
       892, 153, 398, 295,  57, 702, 391, 759, 511, 175, 459, 379, 713,
       755, 530, 617, 233, 450, 188, 644, 626, 704, 197, 252, 279, 129,
       436, 221, 428, 319, 195, 494, 187, 286, 338, 706, 529, 515, 602,
       915, 498, 887, 709, 885, 549, 512, 972, 895, 800, 896, 301, 438,
       947, 476, 527, 298, 171, 315, 374, 482, 592, 272, 871, 383, 213,
       431, 193, 375, 542, 337, 554, 743, 448, 325, 563, 655, 705, 719,
       641, 903, 441, 372, 521, 859, 606, 731, 942, 359, 516, 933, 541,
       845, 856, 403, 974, 842, 299, 588, 768, 918, 813, 846, 492, 447,
       201, 165, 170, 291, 328, 927, 394, 160, 935, 589, 250, 538, 371,
       228, 953, 456, 677, 510, 365, 576, 657, 647, 668, 432, 854, 597,
       378, 507, 306, 380, 577, 579, 437, 392, 167, 251, 430, 181, 340,
       638, 426, 708, 772, 615, 971, 661, 825, 766, 689, 684, 381, 294,
       238, 331, 280, 451, 351, 262, 504, 891, 938, 849, 342, 844, 580,
       733, 522, 481, 646, 651, 987, 878, 386, 866, 413, 913, 443, 599,
       452, 666, 327, 424, 503, 388, 138, 254, 560, 465, 486, 831, 352,
       191, 364, 176, 334, 834, 283, 534, 564, 919, 302, 864, 361, 690,
       754, 711, 499, 943, 790, 872, 939, 594, 717, 897, 449, 788, 317,
       570, 468, 346, 205, 353, 313, 500, 366, 212, 222, 284, 865, 824,
       642, 410, 414, 828, 444, 573, 628, 343, 680, 227, 539, 798, 747,
       483, 796, 822, 555, 526, 253, 401, 217, 330, 767, 820, 665, 268,
       312, 307, 562, 210, 596, 600, 802, 595, 934, 794, 572, 470, 497,
       797, 981, 525, 582, 977, 809, 495, 882, 368, 490, 434, 763, 260,
       488, 419, 369, 350, 618, 778, 305, 421, 922, 873, 830, 976, 762,
       982, 989, 718, 833, 623])

In [ ]:
#8) Dropping unwanted columns
#  df = df.drop([col1,col2,...],axis=1)
df = df.drop("state",axis=1)
df

      year month  no_of_fires      date
0     1998   Jan            0  1/1/1998
1     1999   Jan            0  1/1/1999
2     2000   Jan            0  1/1/2000
3     2001   Jan            0  1/1/2001
4     2002   Jan            0  1/1/2002
...    ...   ...          ...       ...
6449  2012   Dec          128  1/1/2012
6450  2013   Dec           85  1/1/2013
6451  2014   Dec          223  1/1/2014
6452  2015   Dec          373  1/1/2015
6453  2016   Dec          119  1/1/2016

[6292 rows x 4 columns]

In [ ]:
#9)dropping unwanted rows
#  df = df.drop([in1,in2,,.....inn])

df = df.drop([0,1,2])
df

      year month  no_of_fires      date
3     2001   Jan            0  1/1/2001
4     2002   Jan            0  1/1/2002
5     2003   Jan           10  1/1/2003
6     2004   Jan            0  1/1/2004
7     2005   Jan           12  1/1/2005
...    ...   ...          ...       ...
6449  2012   Dec          128  1/1/2012
6450  2013   Dec           85  1/1/2013
6451  2014   Dec          223  1/1/2014
6452  2015   Dec          373  1/1/2015
6453  2016   Dec          119  1/1/2016

[6289 rows x 4 columns]

In [ ]:
#10)resetting the index
#  df.reset_index(inplace=True)
df.reset_index(inplace=True)
df = df.drop("index",axis=1)
df

      year month  no_of_fires      date
0     2001   Jan            0  1/1/2001
1     2002   Jan            0  1/1/2002
2     2003   Jan           10  1/1/2003
3     2004   Jan            0  1/1/2004
4     2005   Jan           12  1/1/2005
...    ...   ...          ...       ...
6284  2012   Dec          128  1/1/2012
6285  2013   Dec           85  1/1/2013
6286  2014   Dec          223  1/1/2014
6287  2015   Dec          373  1/1/2015
6288  2016   Dec          119  1/1/2016

[6289 rows x 4 columns]

In [ ]:
#11) changing the specific data
# df[col] = df[col].str.replace("old","new")

#Task

In [ ]:
df = pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/laptopData.csv")
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   Ram               1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight            1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [ ]:
#handling Nan values
df.dropna(inplace=True)
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [ ]:
#Remove Unnamed: 0 col
df = df.drop("Unnamed: 0",axis=1)
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
#Drop duplicate rows
df.drop_duplicates(inplace=True)
df.shape

(1244, 11)

In [ ]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
#Handling Inches column
df["Inches"] = df["Inches"].replace("?","0")
df["Inches"] = df["Inches"].astype(float)
avg_inch = round(df["Inches"].mean())
df["Inches"] = df["Inches"].replace(0.0,avg_inch)
df["Inches"].unique()

array([13.3, 15.6, 15.4, 14. , 12. , 17.3, 13.5, 12.5, 13. , 18.4, 13.9,
       11.6, 25.6, 35.6, 12.3, 27.3, 24. , 33.5, 15. , 31.6, 17. , 14.1,
       11.3, 10.1])

In [ ]:
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...
1269,Asus,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,4GB,500GB HDD,Nvidia GeForce 920M,Windows 10,2.2kg,38378.6496
1270,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1271,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1272,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1273,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200

In [ ]:
#handling memory column
df["Memory"].mode()
df["Memory"] = df["Memory"].replace("?","256GB SSD")
df["Memory"].unique()

array(['128GB SSD', '128GB Flash Storage', '256GB SSD', '512GB SSD',
       '500GB HDD', '256GB Flash Storage', '1TB HDD',
       '128GB SSD +  1TB HDD', '256GB SSD +  256GB SSD',
       '64GB Flash Storage', '32GB Flash Storage', '256GB SSD +  1TB HDD',
       '256GB SSD +  2TB HDD', '32GB SSD', '2TB HDD', '64GB SSD',
       '1.0TB Hybrid', '512GB SSD +  1TB HDD', '1TB SSD',
       '256GB SSD +  500GB HDD', '128GB SSD +  2TB HDD',
       '512GB SSD +  512GB SSD', '16GB SSD', '16GB Flash Storage',
       '512GB SSD +  256GB SSD', '512GB SSD +  2TB HDD',
       '64GB Flash Storage +  1TB HDD', '180GB SSD', '1TB HDD +  1TB HDD',
       '32GB HDD', '1TB SSD +  1TB HDD', '512GB Flash Storage',
       '128GB HDD', '240GB SSD', '8GB SSD', '508GB Hybrid', '1.0TB HDD',
       '512GB SSD +  1.0TB Hybrid', '256GB SSD +  1.0TB Hybrid'],
      dtype=object)

In [ ]:
#Handling weight column
df["Weight"] = df["Weight"].str.strip("kg")
df["Weight"] = df["Weight"].replace("?","0")
df["Weight"] = df["Weight"].astype(float)
avg_weight = round(df["Weight"].mean())
avg_weight
df["Weight"] = df["Weight"].replace(0.0,avg_weight)
df["Weight"].unique()

In [ ]:
df.reset_index(inplace=True)
df = df.drop("index",axis=1)
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...
1239,Asus,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,4GB,500GB HDD,Nvidia GeForce 920M,Windows 10,2.20,38378.6496
1240,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.80,33992.6400
1241,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.30,79866.7200
1242,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.50,12201.1200
1243,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,40705.9200